apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: budget-certificate-production
  namespace: budget
spec:
  secretName: budget-certificate-production
  issuerRef:
    name: cloudflare-clusterissuer-production
    kind: ClusterIssuer
  commonName: budget.lab.biodrone.xyz
  dnsNames:
    - budget.lab.biodrone.xyz
