apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: budget-ingress
  namespace: budget
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: budget-svc
      port:
        number: 5006
  tls:
    - hosts:
        - budget
