apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: actual-budget-ingressroute
  namespace: actual-budget
  annotations:
    external-dns.alpha.kubernetes.io/target: 10.0.10.21
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`budget.lab.biodrone.xyz`)
      kind: Rule
      services:
        - name: actual-budget-svc
          port: 5006
  tls:
    secretName: actual-budget-certificate-production