apiVersion: v1
kind: Service
metadata:
  name: budget-svc
spec:
  type: ClusterIP
  selector:
    app: budget
  ports:
    - name: http-budget-out
      port: 5006
      protocol: TCP
      targetPort: http-budget
