apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: ntfy-ingress
  namespace: ntfy
  annotations:
    external-dns.alpha.kubernetes.io/target: 10.0.10.21
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`ntfy.lab.biodrone.xyz`)
      kind: Rule
      services:
        - name: ntfy-svc
          port: 80
  tls:
    secretName: ntfy-certificate-production