apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ntfy
resources:
  - namespace.yaml
  - ingressroute-traefik.yaml
  - ingress-tailscale.yaml
  - cert.yaml
  - deployment.yaml
  - svc.yaml
  - pvc.yaml
configMapGenerator:
    - name: server-config
      files: 
        - server.yaml