apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 24h
  # Official Kubernetes SIGs NFS subdir external provisioner chart
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 12h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "~4.0.0"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-provisioner
      interval: 12h
  values:
    replicaCount: 1  # Start with 1 replica - leader election has issues with API server timeouts
    # Resource limits to ensure pod stability
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
    # Run as root to have permissions to create directories on NFS share
    podSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    # Prefer node1 (control plane) for better API server connectivity
    # Using preferredDuringScheduling so it can fallback if node1 is unavailable
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - node1.lab.biodrone.xyz
    nfs:
      server: 192.168.1.250
      path: /mnt/tank/k8s-homelab
    storageClass:
      name: nfs-truenas
      defaultClass: false
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      # Mount options for resilience during NFS server reboots
      mountOptions:
        - hard              # Retry indefinitely if server is down (prevents data corruption)
        - nfsvers=4.1       # Use NFSv4.1 for better features
        - timeo=600         # Timeout for retries (60 seconds)
        - retrans=2         # Number of retries before a "soft" error is reported
        - intr              # Allow interrupts during I/O (helps with hanging processes)
        - noatime           # Don't update access times (improves performance)
      # Optional: add annotations
      # annotations:
      #   storageclass.kubernetes.io/is-default-class: "false"

