apiVersion: v1
kind: Namespace
metadata:
  name: nfs-provisioner
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 24h
  # Official Kubernetes SIGs NFS subdir external provisioner chart
  url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfs-subdir-external-provisioner
  namespace: nfs-provisioner
spec:
  interval: 12h
  chart:
    spec:
      chart: nfs-subdir-external-provisioner
      version: "~4.0.0"
      sourceRef:
        kind: HelmRepository
        name: nfs-subdir-external-provisioner
        namespace: nfs-provisioner
      interval: 12h
  values:
    nfs:
      # TODO: Update with your TrueNAS NFS server details
      server: truenas.lab.biodrone.xyz  # Change to your TrueNAS IP/hostname
      path: /mnt/pool/k8s  # Change to your NFS share path
    storageClass:
      name: nfs-truenas
      defaultClass: false
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      # Mount options for resilience during NFS server reboots
      mountOptions:
        - hard              # Retry indefinitely if server is down (prevents data corruption)
        - nfsvers=4.1       # Use NFSv4.1 for better features
        - timeo=600         # Timeout for retries (60 seconds)
        - retrans=2         # Number of retries before a "soft" error is reported
        - intr              # Allow interrupts during I/O (helps with hanging processes)
        - noatime           # Don't update access times (improves performance)
      # Optional: add annotations
      # annotations:
      #   storageclass.kubernetes.io/is-default-class: "false"

