apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 24h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  releaseName: tailscale
  chart:
    spec:
      chart: tailscale-operator
      version: "~1.82.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  interval: 12h
  install:
    remediation:
      retries: 3
  values:
    # Enable API server proxy to expose Kubernetes control plane over Tailscale
    # auth mode impersonates requests using the sender's tailnet identity for RBAC
    apiServerProxyConfig:
      mode: auth
  # Helm Chart auto mounts the secret named tailscale-oauth in the tailscale namespace
  # https://github.com/tailscale/tailscale/blob/main/cmd/k8s-operator/deploy/chart/templates/deployment.yaml
