---
apiVersion: v1
kind: Namespace
metadata:
  name: traefik
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  dependsOn:
    - name: traefik-crds
  install:
    crds: Skip
  upgrade:
    crds: Skip
  chart:
    spec:
      chart: traefik/traefik
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  values:
    additional:
      checkNewVersion: false
      sendAnonymousUsage: false
    dashboard:
      ingressRoute: false
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik-crds
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik/traefik-crds
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
