---
apiVersion: v1
kind: Namespace
metadata:
  name: vault
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: vault
spec:
  interval: 24h
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 12h
  chart:
    spec:
      chart: vault
      version: "~0.27.0"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
      interval: 12h
  values:
    # Server configuration
    server:
      # Development mode - disabled for production use
      dev:
        enabled: false
      # Standalone mode (single replica) - good for initial setup
      # For production HA, set standalone.enabled: false and enable ha.raft
      standalone:
        enabled: true
      # High Availability mode (disabled for initial setup)
      # Enable this for production with Raft storage backend
      ha:
        enabled: false
        replicas: 3
        # Raft storage backend for HA (requires persistent storage)
        raft:
          enabled: false
      # Data storage configuration for standalone mode
      # Uses file storage backend by default
      # Reference the explicit PVC created above
      dataStorage:
        enabled: true
        existingClaim: vault-data
        # Size and storageClass are ignored when using existingClaim
        # but kept for reference
        size: 10Gi
        storageClass: nfs-truenas
        accessMode: ReadWriteOnce
      # Resource limits
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
    # UI configuration - enables Vault web UI
    ui:
      enabled: true
    # Service configuration
    service:
      enabled: true
      type: ClusterIP
      port: 8200
    # Ingress configuration - using separate IngressRoute resource below
    ingress:
      enabled: false
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-data
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-truenas
  resources:
    requests:
      storage: 10Gi
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-certificate-production
  namespace: vault
spec:
  secretName: vault-certificate-production
  issuerRef:
    name: cloudflare-clusterissuer-production
    kind: ClusterIssuer
  commonName: vault.lab.biodrone.xyz
  dnsNames:
    - vault.lab.biodrone.xyz
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vault-ingressroute
  namespace: vault
  annotations:
    external-dns.alpha.kubernetes.io/target: 10.0.10.21
    kubernetes.io/ingress.class: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.lab.biodrone.xyz`)
      kind: Rule
      services:
        - name: vault
          port: 8200
  tls:
    secretName: vault-certificate-production
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vault-ingress
  namespace: vault
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: vault
      port:
        number: 8200
  tls:
    - hosts:
        - vault

