apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: recipes-postgres
  namespace: recipes
spec:
  serviceName: recipes-postgres
  replicas: 1
  selector:
    matchLabels:
      app: recipes-postgres
  template:
    metadata:
      labels:
        app: recipes-postgres
    spec:
      serviceAccountName: recipes
      securityContext:
        fsGroup: 999
      initContainers:
        - name: init-chmod-data
          image: postgres:18
          command: ['sh', '-c']
          args:
            - |
              # Ensure the PostgreSQL directory has correct ownership
              chown -R 999:999 /var/lib/postgresql
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
      containers:
        - name: postgresql
          image: postgres:18
          securityContext:
            runAsUser: 999
            runAsGroup: 999
          env:
            - name: POSTGRES_DB
              value: recipes
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipes-secrets
                  key: postgresql-postgres-password
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: recipes-postgres-data
  volumeClaimTemplates: []

