apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: recipes-postgres
  namespace: recipes
spec:
  serviceName: recipes-postgres
  replicas: 1
  selector:
    matchLabels:
      app: recipes-postgres
  template:
    metadata:
      labels:
        app: recipes-postgres
    spec:
      serviceAccountName: recipes
      initContainers:
        - name: init-chmod-data
          image: bitnami/postgresql:15
          command: ['sh', '-c']
          args:
            - |
              chown -R 1001:1001 /bitnami/postgresql
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
      containers:
        - name: postgresql
          image: bitnami/postgresql:15
          env:
            - name: POSTGRESQL_DATABASE
              value: recipes
            - name: POSTGRESQL_USERNAME
              value: recipes
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipes-secrets
                  key: postgresql-password
            - name: POSTGRESQL_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: recipes-secrets
                  key: postgresql-postgres-password
          ports:
            - containerPort: 5432
              name: postgresql
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: recipes-postgres-data
  volumeClaimTemplates: []

