apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-static
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi

