# Currently only supported for egress
#https://tailscale.com/kb/1236/kubernetes-operator#optional-pre-creating-a-proxygroup
apiVersion: tailscale.com/v1alpha1
kind: ProxyGroup
metadata:
  name: ts-proxies
spec:
  type: egress
  replicas: 3
