# Example Certificate for podinfo
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: podinfo-certificate-staging
  namespace: podinfo
spec:
  secretName: podinfo-certificate-staging
  issuerRef:
    name: cloudflare-clusterissuer-staging
    kind: ClusterIssuer
  dnsNames:
    - podinfo.lab.biodrone.xyz
