apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
  - cert.yaml
  - ingressroute-traefik.yaml
  - ingress-tailscale.yaml
  - ntfy-alert.yaml
  - discord-alert.yaml