apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    redis:
      enabled: false
      repository: public.ecr.aws/docker/library/redis
      tag: 7.4.2
    ingress:
      enabled: false